- name: Setup EC2 instance
  hosts: ec2
  become: yes
  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present
